In [2]:
import numpy as np

In [4]:
scores=np.array([
    [78,85,62],
    [92,88,95],
    [45,52,58],
    [67,70,74],
    [88,91,84],
    [55,48,60],
    [73,79,81],
    [99,96,90],
])
print(scores)
# Columns math,science,english
# rows- students

[[78 85 62]
 [92 88 95]
 [45 52 58]
 [67 70 74]
 [88 91 84]
 [55 48 60]
 [73 79 81]
 [99 96 90]]


In [16]:
a=np.zeros((2,3),dtype=int)
b=np.ones((2,3),dtype=int)
print(a)
print(b)
c=np.arange(0,10,2)
print(c)
d=np.linspace(0,1,5)
print(d)


[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
None


In [18]:
e=np.random.seed(42)
print(e)
f=np.random.randint(0,100,size=(3,3))
print(f)

None
[[51 92 14]
 [71 60 20]
 [82 86 74]]


In [21]:
print(scores.shape)
print(scores.ndim)
print(scores.size)
print(scores.dtype)

(8, 3)
2
24
int64


In [32]:
print(scores)
ab=scores[0]
print(ab)
print(scores[1,1])
print(scores[:,0])
print(scores[0:4])
print(scores[:,[0,2]])

[[78 85 62]
 [92 88 95]
 [45 52 58]
 [67 70 74]
 [88 91 84]
 [55 48 60]
 [73 79 81]
 [99 96 90]]
[78 85 62]
88
[78 92 45 67 88 55 73 99]
[[78 85 62]
 [92 88 95]
 [45 52 58]
 [67 70 74]]
[[78 62]
 [92 95]
 [45 58]
 [67 74]
 [88 84]
 [55 60]
 [73 81]
 [99 90]]


In [49]:
print(scores.mean())
print(scores.mean(axis=0)) # axis=0 column
print(scores.mean(axis=1)) # axis=1 row
print(scores.max(axis=0))
print(scores.min(axis=0))
print(scores.sum(axis=1))

75.41666666666667
[74.625 76.125 75.5  ]
[75.         91.66666667 51.66666667 70.33333333 87.66666667 54.33333333
 77.66666667 95.        ]
[99 96 95]
[45 48 58]
[225 275 155 211 263 163 233 285]


In [50]:
med=np.median(scores,axis=0)
sd=np.std(scores,axis=0)
ag=np.argmax(scores[:,0])
print(med)
print(sd)
print(ag)

[75.5 82.  77.5]
[17.35610483 16.78866805 13.34166406]
7


In [54]:
print(scores+5)
print(scores*1.1)
print(scores/100)

[[ 83  90  67]
 [ 97  93 100]
 [ 50  57  63]
 [ 72  75  79]
 [ 93  96  89]
 [ 60  53  65]
 [ 78  84  86]
 [104 101  95]]
[[ 85.8  93.5  68.2]
 [101.2  96.8 104.5]
 [ 49.5  57.2  63.8]
 [ 73.7  77.   81.4]
 [ 96.8 100.1  92.4]
 [ 60.5  52.8  66. ]
 [ 80.3  86.9  89.1]
 [108.9 105.6  99. ]]
[[0.78 0.85 0.62]
 [0.92 0.88 0.95]
 [0.45 0.52 0.58]
 [0.67 0.7  0.74]
 [0.88 0.91 0.84]
 [0.55 0.48 0.6 ]
 [0.73 0.79 0.81]
 [0.99 0.96 0.9 ]]


In [55]:
centered=scores-scores.mean(axis=0)
print(centered)

[[  3.375   8.875 -13.5  ]
 [ 17.375  11.875  19.5  ]
 [-29.625 -24.125 -17.5  ]
 [ -7.625  -6.125  -1.5  ]
 [ 13.375  14.875   8.5  ]
 [-19.625 -28.125 -15.5  ]
 [ -1.625   2.875   5.5  ]
 [ 24.375  19.875  14.5  ]]


In [57]:
normalized=(centered)/(scores.max(axis=0)-scores.min(axis=0))
print(normalized)

[[ 0.0625      0.18489583 -0.36486486]
 [ 0.32175926  0.24739583  0.52702703]
 [-0.54861111 -0.50260417 -0.47297297]
 [-0.1412037  -0.12760417 -0.04054054]
 [ 0.24768519  0.30989583  0.22972973]
 [-0.36342593 -0.5859375  -0.41891892]
 [-0.03009259  0.05989583  0.14864865]
 [ 0.45138889  0.4140625   0.39189189]]


In [60]:
# Boolean masking and filtering
print(scores[:,0]>70)
print(scores[scores[:,0]>70])

[ True  True False False  True False  True  True]
[[78 85 62]
 [92 88 95]
 [88 91 84]
 [73 79 81]
 [99 96 90]]


In [62]:
scores[(scores[:,0]>70)&(scores[:,1]>80)&(scores[:,2]>65)]

array([[92, 88, 95],
       [88, 91, 84],
       [99, 96, 90]])

In [65]:
sc=np.where(scores>=60,"pass","fail") # lbel every score
print(sc)
cs=np.sum(scores<60)# how many scores are below 50
print(cs)

[['pass' 'pass' 'pass']
 ['pass' 'pass' 'pass']
 ['fail' 'fail' 'fail']
 ['pass' 'pass' 'pass']
 ['pass' 'pass' 'pass']
 ['fail' 'fail' 'pass']
 ['pass' 'pass' 'pass']
 ['pass' 'pass' 'pass']]
5
